* Introduction
[[https://youtu.be/GoCMYeCHMbQ][YT-Feeder]] is a Rofi-Based RSS Reader made specifically for YouTube video platform. It's written purely in bash and allows user to watch or download new videos.

* Usage

While in the project folder:
#+begin_src bash
chmod +x YT-Feeder
#+end_src

Then to actually run the script:
#+begin_src bash
rofi -show YT-Feeder -modi "YT-Feeder:Absolute/Path/To/YT-Feeder"
#+end_src

I highly suggest binding the above command to your keyboard shortcut of choice. After launch you can select your favorite channel from the list, then select video and then you have a choice to:
- watch(best) -> watch it in the best quality
- watch(worst) -> watch it in the worst quality
- play in the background -> play audio from video in the background
- download -> download the video
- command -> use your custom command on the video's link

There's also an option to refresh the RSS feeds at the top of the list and there might be an option to stop currently playing audio in the background(only after selecting "play in the background").

** Worth noting
The default directory for downloaded videos is ~/Videos/

* Configuration
Change ~/.config/yt-feeder/config file to configure this script. If it doesn't exist, create it. The general syntax for this file is:
#+begin_src
rss link or channel's ID|channel's name
rss link or channel's ID|channel's name
rss link or channel's ID|channel's name
DOWNLOAD|~/Videos/folder_for_yt_videos
COMMAND|my_custom_command
#+end_src
DOWNLOAD and COMMAND lines *must* be at the end of the config file if you wish to use them.
DOWNLOAD specifies the custom directory where you wish to download your videos.
COMMAND specifies your custom command to use on youtube links.

* Requirements
Currently only requirements are:
 - mpv
 - youtube-dl
 - rofi

* TODO TODO
- [] Add information about the number of new videos
- [] Clean bash code
- [x] Add option to change the default directory of downloaded videos
- [x] Add option to play video in the background
- [x] Add an ability to just use channel's ID in the config file
- [x] Add option to use a custom script on selected video
