* Introduction
YT-Feeder is a Rofi-Based RSS Reader made specifically for YouTube video platform(although support for other platforms might come in the future). It's written purely in bash and allows user to watch or download new videos.

* Usage

While in the project folder:
#+begin_src bash
chmod +x YT-Feeder
#+end_src

Then to actually run the script:
#+begin_src bash
rofi -show YT-Feeder -modi "YT-Feeder:Absolute/Path/To/YT-Feeder"
#+end_src

I highly suggest binding the above command to your keyboard shortcut of choice. After launch you can select your favorite channel from the list, then select video and then you have a choice to:
- watch(best) -> watch it in the best quality
- watch(worst) -> watch it in the worst quality
- play in the background -> play audio from video in the background
- download -> download the video

There's also an option to refresh the RSS feeds at the top of the list and there might be an option to stop currently playing audio in the background(only after selecting "play in the background").

** Worth noting
The default directory for downloaded videos is ~/Videos/

* Configuration
Change ~/.config/yt-feeder/config file to configure this script. If it doesn't exist, create it. The general syntax for this file is:
#+begin_src
rss link|channel's name
rss link|channel's name
rss link|channel's name
DOWNLOAD|~/Videos/folder_for_yt_videos
#+end_src
If you wish to change the default directory for downloaded videos like above, then the DOWNLOAD line *must* be at the end of the config file.

* Requirements
Currently only requirements are:
 - mpv
 - youtube-dl
 - rofi

* TODO TODO
- Add option to use a custom script on selected video
- Add information about the number of new videos
- Add an option to paste channel link instead of RSS one(?)
