#!/bin/bash

MAINFOLDER="${HOME}/.config/yt-feeder"
CONFIG="${MAINFOLDER}/config"
CACHE="${HOME}/.cache/yt-feeder"
CACHE_RSS="${HOME}/.cache/yt-feeder/RSS"

f_download () {
    if [[ $# == 2 ]]
    then
        coproc player ( nohup youtube-dl -f "$1" -o "~/Videos/%(title)s.%(ext)s" "$2" > /dev/null 2>&1 ) &&
        cd .
    elif [[ $# == 3 ]]
    then
        CHECK=$( echo "$2" | cut -d '|' -f2 )
        REVERSE=$( echo "$CHECK" | rev )
        if [[ ${REVERSE:0:1} == "/" ]]
        then
            coproc player ( nohup youtube-dl -f $1 -o "$CHECK%(title)s.%(ext)s" "$3" > /dev/null 2>&1 ) &&
            cd .
        else
            coproc player ( nohup youtube-dl -f $1 -o "$CHECK/%(title)s.%(ext)s" "$3" > /dev/null 2>&1 ) &&
            cd .
        fi
    else
        echo "ERROR: Wrong number of arguments passed to the f_download () function"
        exit 1
    fi
}

f_custom () {
    if [[ $# == 1 ]]
    then
        LINK=$( cat "$CACHE/link" )
        coproc player ( nohup $( echo $1 | cut -d '|' -f2 ) "$LINK" > /dev/null 2>&1 ) &&
        cd .
    else
        echo "ERROR: Wrong number of arguments passed to the f_custom () function"
        exit 1
    fi
}

f_check_pid () {
    if [ -f "$CACHE/pid" ]
    then
        if [[ $# == 0 ]]
        then
            PID_n=$( cat "$CACHE/pid" )
            kill $PID_n
        elif [[ $# == 1 ]]
        then
            PID_n=$( cat "$CACHE/pid" )
            if kill -0 $PID_n ;
            then
                echo "$1";
            else
                rm "$CACHE/pid";
            fi
        else
            echo "ERROR: Wrong number of arguments passed to the f_check_pid () function"
            exit 1
        fi
    fi
}

if [ $# -eq 0 ]
then
    if [ ! -d "$MAINFOLDER" ]
    then
        mkdir -p "$MAINFOLDER"
        touch "$CONFIG"
    fi
    if [ ! -f "$CONFIG" ]
    then
        touch "$CONFIG"
    fi
    if [ ! -d "$CACHE_RSS" ]
    then
        mkdir -p "$CACHE_RSS"
    fi
fi

if [ $# -eq 0 ]
then
    f_check_pid "stop"
    echo "refresh(it may take a while)"
    ls -1 "$CACHE_RSS" | sed "s/^/-> /"
else
    if [ x"$@" = x"refresh(it may take a while)" ]
    then
        if [ -f $CONFIG ]
        then
            rm "$CACHE_RSS"/*
            LENGTH=$( wc -l $CONFIG )
            while read p; do
                if [ -z "$p" ]
                then
                    continue
                fi
                FEED=$( echo $p )
                if [[ ! "${FEED:0:19}" == "https://www.youtube" && ! "${p:0:8}" == "DOWNLOAD" && ! "${p:0:7}" == "COMMAND" && ! "${FEED:0:2}" == "//" ]]
                then
                    FEED=$( echo "https://www.youtube.com/feeds/videos.xml?channel_id=$FEED" )
                fi
                if [[ ! "${p:0:8}" == "DOWNLOAD" && ! "${p:0:7}" == "COMMAND" && ! "${FEED:0:2}" == "//" ]]
                then
                    wget $FEED -O "$CACHE_RSS/TMP" &&
                    NAME=$( cat "$CACHE_RSS/TMP" | grep "<title>" | sed -e :a -e 's/<[^>]*>//g;/</N;//ba' | head -n 1 | sed 's/^ *//' )
                    mv "$CACHE_RSS/TMP" "$CACHE_RSS/$NAME"
                fi
            done < $CONFIG
        fi
        f_check_pid "stop"
        ls -1 "$CACHE_RSS" | sed "s/^/-> /"
    elif [ x"$@" = x"stop" ]
    then
        f_check_pid
    elif [ x"$@" = x"watch(best)" ]
    then
        LINK=$( cat "$CACHE/link" )
        coproc player ( nohup mpv --ytdl-format=best "$LINK" > /dev/null 2>&1 ) &&
        rm "$CACHE/link"
    elif [ x"$@" = x"watch(worst)" ]
    then
        LINK=$( cat "$CACHE/link" )
        coproc player ( nohup mpv --ytdl-format=worst "$LINK" > /dev/null 2>&1 ) &&
        rm "$CACHE/link"
    elif [ x"$@" = x"download" ]
    then
        LINK=$( cat "$CACHE/link" )
        while read p; do
            if [[ "${p:0:8}" == "DOWNLOAD" ]]
            then
                f_download "best" "${p:9}" "$LINK"
                exit 0
            fi
        done < "$CONFIG"
        f_download "best" "$LINK"
    elif [ x"$@" = x"download audio" ]
    then
        LINK=$( cat "$CACHE/link" )
        cat "$CONFIG" | tail -n3 > "$CACHE/TMP"
        while read p; do
            if [[ "${p:0:14}" == "DOWNLOAD_AUDIO" ]]
            then
                f_download "bestaudio" "${p:15}" "$LINK"
                exit 0
            fi
        done < "$CONFIG"
        f_download "bestaudio" "~/Music" "$LINK"
    elif [ x"$@" = x"play in the background" ]
    then
        f_check_pid
        LINK=$( cat "$CACHE/link" )
        coproc player ( nohup mpv --no-video "$LINK" > /dev/null 2>&1 ) &&
        rm "$CACHE/link"
        echo ${player_PID} > "$CACHE/pid"
    elif [ x"$@" = x"custom" ]
    then
        cat "$CONFIG" | tail -n3 > "$CACHE/TMP"
        while read p; do
            if [[ "${p:0:7}" == "COMMAND" ]]
            then
                f_custom "$p"
                break
            fi
        done < "$CONFIG"
    else
        CHECK=$@
        if [ x${CHECK:0:2} = x"->" ]
        then
            echo ${CHECK:3} > "$CACHE/last"
            TAG="media:title"
            cat "$CACHE_RSS/${CHECK:3}" | grep "<title>" | sed -e :a -e 's/<[^>]*>//g;/</N;//ba' | tail -n +2 | sed 's/\&quot;/\"/g' | sed 's/\&amp;/\&/g'
        else
            TITLE=$( cat "$CACHE/last" )
            VIDEO=$( echo "$@" | sed 's/\"/quot;/g' | sed 's/\&/\&amp;/g' | sed 's/quot;/\&quot;/g' )
            VIDEO=${VIDEO:2}
            LINK=$( cat "$CACHE_RSS/$TITLE" | grep -A 1 "<title>$VIDEO" | tail -n1 | sed -r 's/^.+href="([^"]+)".+$/\1/' )
            echo $LINK > "$CACHE/link"
            echo "watch(best)"
            echo "watch(worst)"
            echo "play in the background"
            echo "download"
            echo "download audio"
            echo "custom"
        fi
    fi
fi
